export const sponsors = [
  {
    Partner: "Associate Title Sponsor",
    PartnerName: "TATA Motors",
    Link: "https://www.tatamotors.com/",
    Logo: "",
  },
  {
    Partner: "Offical Powered by Sponsor",
    PartnerName: "Quick Smart Wash",
    Link: "https://www.quicksmartwash.com/",
    Logo: "../logos/quicksmartwash.png",
  },
  {
    Partner: "Offical Gold Sponsor",
    PartnerName: "Walmart",
    Link: "https://www.walmart.com/",
    Logo: "../logos/walmart.png",
  },
  {
    Partner: "Official Engineering Design Partner",
    PartnerName: "Autodesk",
    Link: "https://www.autodesk.in/",
    Logo: "../logos/autodesk.png",
  },
  {
    Partner: "Offical Drone Technology Partner",
    PartnerName: "BotLab Dynamics",
    Link: "https://botlabdynamics.com/",
    Logo: "../logos/Botlab.png",
  },
  {
    Partner: "Official Community Partner",
    PartnerName: "BuidlersTribe",
    Link: "https://buidlerstribe.com/",
    Logo: "../logos/BuidlersTribe.png",
  },
  {
    Partner: "Official Financial Wellness Partner",
    PartnerName: "FinMapp",
    Link: "https://www.finmapp.com/",
    Logo: "../logos/finmapp.png",
  },
  {
    Partner: "Associate Partner",
    PartnerName: "Google Developers",
    Link: "https://developers.google.com/",
    Logo: "../logos/google_developers_PNG.png",
  },
  {
    Partner: "Offical Social Media Partner",
    PartnerName: "BeReal",
    Link: "https://bereal-app.typeform.com/BitsPilani",
    Logo: "../logos/WhatsApp Image 2023-03-22 at 4.08.32 PM.jpeg",
  },
  {
    Partner: "Gaming Partner",
    PartnerName: "ASUS",
    Link: "https://www.asus.com/in/",
    Logo: "../logos/asus.png",
  },
  {
    Partner: "Offical Sponsor",
    PartnerName: "Hubhoppper",
    Link: "https://hubhopper.com/",
    Logo: "../logos/Hubhopper.png",
  },
  {
    Partner: "Offical Mentorship Partner",
    PartnerName: "Metvy",
    Link: "https://www.metvy.com/",
    Logo: "../logos/metvy.png",
  },
  {
    Partner: "Offical Banking Partner",
    PartnerName: "HDFC",
    Link: "https://www.hdfcbank.com/",
    Logo: "../logos/HDFC.svg",
  },
  {
    Partner: "Offical Event Partner",
    PartnerName: "Samaro",
    Link: "https://www.samaro.app/",
    Logo: "../logos/samaro.png",
  },
  {
    Partner: "Official Sponsor",
    PartnerName: "Labdox",
    Link: "https://www.labdox.com/",
    Logo: "../logos/Labdox.jpeg",
  },
  {
    Partner: "Offical Snacking Partner",
    PartnerName: "Too Yumm",
    Link: "https://www.tooyumm.com/",
    Logo: "../logos/tooyumm.png",
  },
  {
    Partner: "Official Beverage Partner",
    PartnerName: "Continental Coffee",
    Link: "https://www.cclproducts.com/",
    Logo: "../logos/continental.jpg",
  },
  {
    Partner: "Official Grooming Partner",
    PartnerName: "Beardo",
    Link: "https://beardo.in",
    Logo: "../logos/beardo.jpg",
  },
  {
    Partner: "Offical Energy Coffee Partner",
    PartnerName: "Hell Energy",
    Link: "https://www.hellenergy.com/",
    Logo: "../logos/HELL.png",
  },
  {
    Partner: "Offical Fragrance Partner",
    PartnerName: "French Factor",
    Link: "https://french-factor.com/",
    Logo: "../logos/frenchfactor.png",
  },
  {
    Partner: "Official Juice Partner",
    PartnerName: "Raw Pressery",
    Link: "https://www.rawpressery.com/",
    Logo: "",
  },
  {
    Partner: "Official Sweets Partner",
    PartnerName: "Dobiee",
    Link: "",
    Logo: "",
  },
  {
    Partner: "Official CaseComp Partner",
    PartnerName: "E-Learnmarkets",
    Link: "https://www.elearnmarkets.com/",
    Logo: "../logos/stockedge.jpeg",
  },
  {
    Partner: "Offical Knowledge Partner",
    PartnerName: "LWT",
    Link: "https://learningwhiletravelling.com/",
    Logo: "../logos/001_LWT_logo.png",
  },
  {
    Partner: "Offical Music Production Partner",
    PartnerName: "SoundIdeaz",
    Link: "https://www.soundideazacademy.in/",
    Logo: "../logos/Soundideaz.png",
  },
  {
    Partner: "Offical Travel Partner",
    PartnerName: "EaseMyTrip",
    Link: "https://www.easemytrip.com/",
    Logo: "../logos/White Logo.png",
  },
  {
    Partner: "",
    PartnerName: "Fabwelt",
    Link: "",
    Logo: "",
  },
  {
    Partner: "",
    PartnerName: "GrabOn",
    Link: "https://www.grabon.in/",
    Logo: "../logos/GrabOn.png",
  },
  {
    Partner: "Official Hosting Partner",
    PartnerName: "Spheron",
    Link: "https://spheron.network/",
    Logo: "../logos/spheron.png",
  },
  {
    Partner: "Official Cross Chain Partner",
    PartnerName: "Router Protocol",
    Link: "https://www.routerprotocol.com/",
    Logo: "../logos/routerProtocol.svg",
  },
];
